import fs from "fs"
import path from "path"

const IGNORE = [
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  "coverage"
]

function buildTree(dir, depth = 0) {
  const files = fs.readdirSync(dir)

  let tree = ""

  files
    .filter(f => !IGNORE.includes(f))
    .forEach(file => {

      const full = path.join(dir, file)
      const stat = fs.statSync(full)

      const indent = "  ".repeat(depth)

      if (stat.isDirectory()) {
        tree += `${indent}- 📁 ${file}\n`
        tree += buildTree(full, depth + 1)
      } else {
        tree += `${indent}- 📄 ${file}\n`
      }

    })

  return tree
}

export function generateRepoMap() {
  const tree = buildTree(process.cwd())

  return `
# Repository Map

This document provides a quick overview of the repository structure.

It is used by developers and AI agents to understand where code lives.

## Root Structure

${tree}

## Notes

- node_modules, build artifacts and git folders are excluded
- This file is automatically generated by ai-bootstrap
`
}